### ISSUE TITLE
 No such file or directory: 'checkpoint\\d-pt-243.bin'

### ISSUE THREAD

**Issue by Myeongsuk** [tobiascz/VideoPose3D#1]
![image](https://user-images.githubusercontent.com/47096221/53460380-433ff280-3a80-11e9-9fca-55dad24e2db4.png)
![image](https://user-images.githubusercontent.com/47096221/53460387-4e931e00-3a80-11e9-9ff5-c08a55c56ff4.png)

could you help me?

**Comment by ultra-sonic** [comment]
wget https://dl.fbaipublicfiles.com/video-pose-3d/d-pt-243.bin
