### ISSUE TITLE
Hip Joint not moving in Skater Video

### ISSUE THREAD

**Issue by InzamamAnwar** [tobiascz/VideoPose3D#11]
Thank you for you hard work in developing this repo. After studying and running your code, my question is why hip joint/pelvis joint is not moving in the output video. Furthermore there seems to be no translational motion in the output. Is it due to plot technique you have used or something else?

**Comment by tobiascz** [comment]
The hip joint does not move in this representation. This is a very common convention for visualization of 3D human poses. To traject your 3D pose, you can use the trajectory of your input 2D pose.

**Comment by InzamamAnwar** [comment]
Okay thank you for your clarification.
