### ISSUE TITLE
How to train？

### ISSUE THREAD

**Issue by li2058088** [tobiascz/VideoPose3D#12]
Hello! Thanks a lot for the work you've done!
I want to know how to train the model and what you have done with the h36m dataset.

**Comment by tobiascz** [comment]
For training it is best to check out the authors repository: https://github.com/facebookresearch/VideoPose3D

`python run.py -e 80 -k cpn_ft_h36m_dbb -arc 3,3,3,3,3`

This is where the training is started.

**Comment by li2058088** [comment]
Think you.
