### ISSUE TITLE
3d coordinates

### ISSUE THREAD

**Issue by szdxcjh** [tobiascz/VideoPose3D#14]
Hi，i wonder can this output 3d coordinates?
thanks for helping me.

**Comment by tobiascz** [comment]
Yes, exactly. It takes 2D input coordinates and creates 3D output coordinates.

https://github.com/tobiascz/VideoPose3D/blob/910f78c9995a40198b242a4a7aaacecc397d7077/run_wild.py#L303

I save a 3D coordinates file in the dev branch if you need an example on how to save the 3D coordinates

**Comment by szdxcjh** [comment]
oh,thanks！

**Comment by hellozjj** [comment]
> Yes, exactly. It takes 2D input coordinates and creates 3D output coordinates.
> 
> https://github.com/tobiascz/VideoPose3D/blob/910f78c9995a40198b242a4a7aaacecc397d7077/run_wild.py#L303
> 
> I save a 3D coordinates file in the dev branch if you need an example on how to save the 3D coordinates

Does it have the root 3D world position?
