### ISSUE TITLE
can not split the video

### ISSUE THREAD

**Issue by szdxcjh** [tobiascz/VideoPose3D#15]
Hi,
I wanted to repeat your operation but I got the error when I inputed this:
ffmpeg-i out_cutted.mp4-r 25/1 splited_scating/output%04d.png
![image](https://user-images.githubusercontent.com/48876095/61018637-13a7dc00-a3ca-11e9-81a8-c1b0ef77976e.png)

**Comment by tobiascz** [comment]
in which directory are you running ffmpeg? Which files are in this directory?
Try to create the empty folder "splitted_scating" manually and rerun the code maybe ffmpeg doesn't have the rights to create a folder.

**Comment by szdxcjh** [comment]
Thanks for your answer
