### ISSUE TITLE
Output interactive 3D plot

### ISSUE THREAD

**Issue by spoonerj** [tobiascz/VideoPose3D#16]
Hi, 

This is some great work!
I have been unable to get the Detectron working (I use windows) so I have been using AlphaPose to do my 2D pose estimations, then I have attempted to put it in the same format as the 'data_2d_detections.npz' that you provided.

I have 2 questions:
In the data_2d_detections.npz which you provide for the Ice Skater, when I unpack the file, there are 3 dimensions, what is the third dimension in this file, as I understand it is only giving 2D pose estimates?

Secondly, is there a way which I can run the 3D estimator and output only the 3D plot, but in such a way that it is interactive like with other 3D plots in matplotlib. (I have been trying to do this myself, semi-successfully; where I can output a live 3D animation of the output file  'out_3D_vp3d.npz', but I am unable to construct the skeleton).

Your help is very much appreciated!

spoonerj

**Comment by tobiascz** [comment]
1. question:
This is a post by the author of this method: https://github.com/facebookresearch/VideoPose3D/issues/2#issuecomment-444687031
the third value is the probability score of the heatmap. Basically the confidence of the method.

2. question: 
It is definitely possible to draw the output in your own 3D plot. All the updates to the 3D plot are done here:
https://github.com/tobiascz/VideoPose3D/blob/b650bf894f36e04c39db4351e38656929f763a43/common/visualization.py#L55
you basically would need to add more parameters to update. Maybe its easier to rewrite your own visualization function. For debugging I basically drew the skeleton with 1 joint than with 2 then with 3 and so on so I could understand which index belongs to which joint. This was a bit tricky I have to admit.

Hope I could help.
