### ISSUE TITLE
About] Splitting command

### ISSUE THREAD

**Issue by GyosunShin** [tobiascz/VideoPose3D#18]
Hello Thank you for your Awesome Work!

i used Splitting command:  ffmpeg -i ice.mp4 -r 25/1 splitted_scating/output%04d.png as you attached
to get each frame images for my own mp4 video file.
I want to know what 25/1 means... does this mean 25frames for 1 sec?

Thank you

**Comment by tobiascz** [comment]
honestly the 25/1 == 25.
In the FFMPEG manual they write:
```
-r[:stream_specifier] fps (input/output,per-stream)
Set frame rate (Hz value, fraction or abbreviation).

As an input option, ignore any timestamps stored in the file and instead generate timestamps assuming constant frame rate fps. This is not the same as the -framerate option used for some input formats like image2 or v4l2 (it used to be the same in older versions of FFmpeg). If in doubt use -framerate instead of the input option -r.

As an output option, duplicate or drop input frames to achieve constant output frame rate fps.
```

so you could interprete 25 as input and 1 as output. so for every 1 second of movie create 25 images.
in case of 25/2 you create exactly half the amount of images, for every 2 seconds create 25 images. 
But this is a stupid way to think about it. Its easier to use 25 or 12fps directly. 
I will remove the /1 from it. Thanks for pointing it out.
