### ISSUE TITLE
Download the weights file with the coco keypoints

### ISSUE THREAD

**Issue by ultra-sonic** [tobiascz/VideoPose3D#2]
Hi Tobias,
I get errors running detectron and I have a feeling this is because I am using the wrong weights.
Can you point me to the correct weights file that I need to use with "e2e_keypoint_rcnn_R-101-FPN_s1x.yaml"
I am using "R-101.pkl" from here https://dl.fbaipublicfiles.com/detectron/ImageNetPretrained/MSRA/R-101.pkl
but detectron tells me:
`
INFO net.py:  96: res5_2_branch2c_bn_s loaded from weights file into gpu_0/res5_2_branch2c_bn_s: (2048,)
INFO net.py:  96: res5_2_branch2c_bn_b loaded from weights file into gpu_0/res5_2_branch2c_bn_b: (2048,)
INFO net.py:  89: fpn_inner_res5_2_sum_w not found
INFO net.py:  89: fpn_inner_res5_2_sum_b not found
INFO net.py:  89: fpn_inner_res4_22_sum_lateral_w not found
`
....
`
[E net_async_base.cc:377] IsType<T>() ASSERT FAILED at /pytorch/aten/src/ATen/core/blob.h:77, please report a bug to PyTorch. wrong type for the Blob instance. Blob contains nullptr (uninitialized) while caller expects caffe2::Tensor.
Offending Blob name: gpu_0/fpn_inner_res2_2_sum_lateral_w.
....
`

any help would be greatly appreciated!

**Comment by tobiascz** [comment]
I don't know where I got this file from anymore. I think it was somewhere described in the videopose3D repository. I uploaded my local one to dropbox so maybe just use that. Let me know if it works!

[model](https://www.dropbox.com/sh/vi5byf0du9g50lw/AABGVezeuHuipOzaFGdGGvbaa?dl=0)

**Comment by ultra-sonic** [comment]
thanks you so very much for your quick help! it is running properly now!

**Comment by ultra-sonic** [comment]
I think this is what I was looking for:
https://github.com/facebookresearch/Detectron/blob/master/MODEL_ZOO.md
It contains links to all models they have trained so far at facebook.

**Comment by fizzerle** [comment]
Which file did you choose? I get the same error as in the first post.

**Comment by tzvsi** [comment]
Try this:

```
https://dl.fbaipublicfiles.com/detectron/37698009/12_2017_baselines/e2e_keypoint_rcnn_R-101-FPN_s1x.yaml.08_45_57.YkrJgP6O/output/train/keypoints_coco_2014_train:keypoints_coco_2014_valminusminival/generalized_rcnn/model_final.pkl
```
