### ISSUE TITLE
can not turn this video pose estimate to a real time pose estimate?

### ISSUE THREAD

**Issue by DangerIgnore** [tobiascz/VideoPose3D#20]
Thank you for your project. I have basically completed the code operation and tested my own video.I now have some questions:
1. if i want to get a more accurate 3D attitude data, do i need to basically keep the camera in order to get a relatively determined global trajectory?
2. Can this project be changed to real-time pose estimate just like the VNect project? if
so,I hope the author can provide some suggestions and opinions.
wish your reply.

**Comment by tobiascz** [comment]
1. I am not sure what you mean with this. If you you change the camera of course the trajectory is also translated so you would need to correct that.
2. In the paper they mention a way of doing this:
<img width="431" alt="image" src="https://user-images.githubusercontent.com/8737489/66469850-f4801f80-ea88-11e9-8ebc-1f3329f1a8b9.png">
The causal convolutions do not depend on future frames (unlike the symmetric one) and can therefore be used for realtime applications.
https://arxiv.org/pdf/1811.11742.pdf

But there is no running code for that so you would need to program that yourself.
