### ISSUE TITLE
I want to know the prediction of output has joints' world position or not?

### ISSUE THREAD

**Issue by hellozjj** [tobiascz/VideoPose3D#22]
I want to know the prediction of output has joints' world position or not because I want to visualize all joints' movement including the root?
So, if the prediction has all joints' world position, does it include the root positon?
Thanks for any answer!

**Comment by hellozjj** [comment]
And how the joints rank in the prediction?

**Comment by tobiascz** [comment]
have a look at [this](https://github.com/facebookresearch/VideoPose3D/issues/75)
