### ISSUE TITLE
Reproducing paper results from scratch?

### ISSUE THREAD

**Issue by alecda573** [tobiascz/VideoPose3D#27]
I have been trying  to reproduce the results for the 27,81,243 frame models  on cpn detections and have continued to fail. Do you have a training log and hyperparameter config that hits the results in the paper that you  would be willing to share?

**Comment by tobiascz** [comment]
In this repository I simply provide a way to run the prediction of the model on your own images. For checkpoints and bechnmarking you should check in the original repository. https://github.com/facebookresearch/VideoPose3D
