### ISSUE TITLE
Incorrect output on skater

### ISSUE THREAD

**Issue by amritap196** [tobiascz/VideoPose3D#3]
I followed the instructions to run on the ice skating video (4 onwards) and this is the output I got.
![output](https://user-images.githubusercontent.com/11476151/54269313-0fcb9080-4575-11e9-9806-ee0a868bd27d.gif)

Any help would be much appreciated! I'm not quite sure what I did wrong.

**Comment by tobiascz** [comment]
look at the input 2D points in the skater video on the left. Your 2D points do not match the scater girl. I think you have to rebuild the 2D keypoint file for the scater (run detectron on scater video).

**Comment by tobiascz** [comment]
I updated the [data_2d_detections.npz](https://github.com/tobiascz/VideoPose3D/blob/master/data/data_2d_detections.npz) file. It should work now!

**Comment by amritap196** [comment]
Great yes that does work now, thank you!
