### ISSUE TITLE
Not able to get accurate output on own video (walking)

### ISSUE THREAD

**Issue by amritap196** [tobiascz/VideoPose3D#5]
Hi, 

I have used Detectron to obtain the 2D key points  on my own video(which seem accurate enough, just too fast on the overlay of the video) - and then ran VideoPose to obtain 3D keypoints. It doesn't really seem to work that well on this video - not even the unoccluded arm is captured properly. 

Any thoughts as to why this is happening?

![output](https://user-images.githubusercontent.com/11476151/54854502-09fb4b00-4ceb-11e9-909e-5f2d21bec7cb.gif)

Many thanks for any help/advice that can be offered,
Amrita

**Comment by tobiascz** [comment]
I would first try to fix the obvious stuff. 
Fix the framerate: as you can see the 2d keypoints are faster than your video so find out the framerate of your video and adjust the parameter in the code. 
The 3D estimation really looks poorly. Try a video with a front facing person first. If this works continue with more difficult poses like a side view. Also there is a Parameter for width and height of the video you use in the code also adjust that to match your video! 

I hope I could help!
