### ISSUE TITLE
Having troubles understanding pipeline

### ISSUE THREAD

**Issue by SergeiGorbatiuk** [tobiascz/VideoPose3D#6]
Hello! Thanks a lot for the work you've done!
I faced some troubles understanding what actions should actually be done to reproduce results on my own video as notes from README seems quite ambiguous for me(
Firstly, is it intended to run the initial detectron sources from https://github.com/facebookresearch/Detectron on the folder with cut video? 
I didn't quite get what's that absolute path `/detectron/videopose3d/...` in
```
python infer_simple.py --cfg /detectron/videopose3d/e2e_keypoint_rcnn_R-101-FPN_s1x.yaml --output-dir demo/scating_vis --image-ext jpg --wts /pathToYourWeightFile/keypoints_coco_2014_train:keypoints_coco_2014_valminusminival/model_final.pkl
demo/splitted_scating
```
is it a path to a detectron on my machine?
Secondly, why is it said that I should replace the `infer_simple.py` in your repo with the one from detectron repo (?)

**Comment by tobiascz** [comment]
I am sorry to hear that you have troubles.
The infer_simple.py provided by detectron works fine and outputs for each frame a file image with the detections for this frame. For VideoPose3D however, you need a .npz file with all the frames 2D positions and that is exactly what I added at the modified version of [infer_simple](https://github.com/tobiascz/VideoPose3D/blob/master/detectron_tools/infer_simple.py) best you compare them side by side.

```parser = argparse.ArgumentParser(description='End-to-end inference')
    parser.add_argument(
        '--cfg',
        dest='cfg',
        help='cfg model file (/path/to/model_config.yaml)',
        default=None,
        type=str
    )
    parser.add_argument(
        '--wts',
        dest='weights',
        help='weights model file (/path/to/model_weights.pkl)',
        default=None,
        type=str
    )
    parser.add_argument(
        '--output-dir',
        dest='output_dir',
        help='directory for visualization pdfs (default: /tmp/infer_simple)',
        default='/tmp/infer_simple',
        type=str
    )
    parser.add_argument(
        '--image-ext',
        dest='image_ext',
        help='image file name extension (default: jpg)',
        default='jpg',
        type=str
    )
    parser.add_argument(
        '--always-out',
        dest='out_when_no_box',
        help='output image even when no object is found',
        action='store_true'
    )
    parser.add_argument(
        '--output-ext',
        dest='output_ext',
        help='output image file format (default: pdf)',
        default='pdf',
        type=str
    )
    parser.add_argument(
        '--thresh',
        dest='thresh',
        help='Threshold for visualizing detections',
        default=0.7,
        type=float
    )
    parser.add_argument(
        '--kp-thresh',
        dest='kp_thresh',
        help='Threshold for visualizing keypoints',
        default=2.0,
        type=float
    )
    parser.add_argument(
        'im_or_folder', help='image or folder of images', default=None
    )
    if len(sys.argv) == 1:
        parser.print_help()
        sys.exit(1)
    return parser.parse_args()
 ```

Those are the arguments for the infer_simple.py program. As described in the readme:
[Download the config-file (specified by --cfg flag) you will need it for detectron.](https://github.com/tobiascz/VideoPose3D) 

/detectron/videopose3d/ specifies the custom config file for detectron that is required to estimate coco keypoints.

**Comment by SergeiGorbatiuk** [comment]
So, am I right that I should use original detectron repository with `infer_simple.py` written by you, provide weights and config that you mention in README to it, and then use your repository to run VideoPose on output from the detecrtron?

**Comment by tobiascz** [comment]
Yes - that is basically the pipeline for this fork of the original code.

**Comment by SergeiGorbatiuk** [comment]
Thank you again, I will try:)
