### ISSUE TITLE
Redundant line in `infer_simple.py`

### ISSUE THREAD

**Issue by SergeiGorbatiuk** [tobiascz/VideoPose3D#7]
There are lines in the end of `infer_simple.py`:
```
np.savez(os.path.join('/home/narvis/Dev/VideoPose3D/data', "data_2d_detections.npz"), metadata=metadata, positions_2d=dictionarry_keypoints) 
np.savez(os.path.join(args.output_dir, "data_2d_detections.npz"), metadata=metadata, positions_2d=dictionarry_keypoints)
```
Obviously, the first one is redundant and left here in the process of development/debugging/etc. Of course, it causes a crush with FileNotFoundError, and, although the fix is clear for anyone looking at the stacktrace, I think is better to remove this line, as the crush happens right before saving precious results, but after processing frames, which is time-consumig;)

**Comment by tobiascz** [comment]
That is true and especially painful for very long sequences. I commented that [line](https://github.com/tobiascz/VideoPose3D/commit/f30d00f9b1488d354cc548fe66b3b5fe1620b6cc#diff-6669a0d6ccde7dbc01de9aa4ecbdd62c) to resolve the issue.
Thanks!
