### ISSUE TITLE
Checkpoint file in readme doesn't work 

### ISSUE THREAD

**Issue by mjsampson** [tobiascz/VideoPose3D#8]
OS: Ubuntu 16.04 
Envrionment: docker from pytorch/pytorch:1.0-cuda10.0-cudnn7-runtime

Hello, 

I am researching into view invariant 3d pose detection with the University of New Brunswick for it's applications in senior mobility and we are running your "in the wild" code! The [link](https://s3.amazonaws.com/video-pose-3d/d-pt-243.bin) you have in your [README](https://github.com/tobiascz/VideoPose3D/blob/master/README.md) no longer points to an active server and when I download the checkpoint file of the pretrained model from [the source github account](https://github.com/facebookresearch/VideoPose3D/blob/master/README.md) I get the following error

```
topiascz    | INFO: Trainable parameter count: 17004595
topiascz    | Loading checkpoint checkpoint/pretrained_h36m_cpn.bin
topiascz    | This model was trained for 80 epochs
topiascz    | Traceback (most recent call last):
topiascz    |   File "/project/subtree/tobiasc/run_wild.py", line 185, in <module>
topiascz    |     model_pos.load_state_dict(checkpoint['model_pos'])
topiascz    |   File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 769, in load_state_dict
topiascz    |     self.__class__.__name__, "\n\t".join(error_msgs)))
topiascz    | RuntimeError: Error(s) in loading state_dict for TemporalModel:
topiascz    | 	size mismatch for expand_conv.weight: copying a param with shape torch.Size([1024, 34, 3]) from checkpoint, the shape in current model is torch.Size([1024, 51, 3]).
topiascz exited with code 1
```

Do you happen to have a link to the checkpoint file you used with your run_wild.py code. If not would simply editing the model.py file work?

Thankyou,

Matthew Sampson

**Comment by tobiascz** [comment]
I'm glad to hear that the code is used! [correct weights file](https://dl.fbaipublicfiles.com/video-pose-3d/d-pt-243.bin) that should be the right one. You can find more Info [here](https://github.com/facebookresearch/VideoPose3D/issues/2). I hope you don't have any further issues! I also updated the README with the modified links.

Cheers
